---
# File: tasks/dnsmasq.yml - Dnsmasq tasks for Consul

- name: Dnsmasq package
  yum: name=dnsmasq state=present
  when: ansible_os_family == "RedHat"
  tags: dnsmasq,installation

- debug: var=ansible_os_family

- name: Dnsmasq package
  apt: name=dnsmasq state=present
  when: ansible_os_family == "Debian"
  tags: dnsmasq,installation

- debug: var=ansible_os_family

- name: Stop Dnsmasq
  service: name=dnsmasq state=stopped

- name: "Dnsmasq setup"
  copy: src=../files/dnsmasq-10-consul dest=/etc/dnsmasq.d/10-consul owner=root group=root mode=0644
  notify: restart dnsmasq
  tags: dnsmasq
